name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm deps
        working-directory: app
        run: npm ci

      - name: Build web assets (optional)
        working-directory: app
        run: npm run build || true

      - name: Capacitor sync
        working-directory: app
        run: npx cap sync android

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # *** WICHTIG: nur notwendige Android-Pakete, kein Emulator ***
      - name: Setup Android SDK (lean)
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      # Gradle-Cache (beschleunigt Folge-Runs)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        working-directory: app/android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neo-hydraulik-debug-apk
          path: app/android/app/build/outputs/apk/debug/app-debug.apk
