name: Android Debug APK
on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - ".github/workflows/apk-debug.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build web (optional) & Capacitor sync
        working-directory: app
        run: |
          npm ci
          npm run build || true
          npx cap sync android

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android components
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Preflight gradlew
        working-directory: app/android
        run: |
          pwd
          ls -la
          test -f gradlew || (echo "❌ gradlew fehlt in app/android" && exit 1)
          chmod +x gradlew
          ./gradlew --version

      - name: Build debug APK
        working-directory: app/android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neo-hydraulik-debug-apk
          path: app/android/app/build/outputs/apk/debug/app-debug.apk
